### ISSUE TITLE
Property has errors?

### ISSUE THREAD

**Issue by timmather** [ombakke/KS.Umbraco7.Calendar#2]
I did a fresh install against a new doc type, when I create a node I get what looks like a validation error but haven't marked as mandatory and can't get round it. Umbraco 7.2.1? Any ideas.

**Comment by timmather** [comment]
Just realised it is something to do with the date format if I manually enter 2015-02-05 21:01:04 it saves, the format your pickers are using is different?

**Comment by ombakke** [comment]
Fixed by upgrading/changing datetime-picker
